package doga.betterComponents;

import java.awt.Color;

/**
 * Predefined colors for various components.
 * 
 * @author Doða Oruç
 * @verison 07.03.2018
 */
public class BetterColors {

	public static Color NO_COLOR = BetterColorConstants.NO_COLOR;

	public static Color MENU_BAR_BG_COLOR = BetterColorConstants.MENU_BAR_BG_COLOR;

	public static Color MENU_BG_COLOR = BetterColorConstants.MENU_BG_COLOR;
	public static Color MENU_FG_COLOR = BetterColorConstants.MENU_FG_COLOR;
	public static Color MENU_SELECTION_BG_COLOR = BetterColorConstants.MENU_SELECTION_BG_COLOR;
	public static Color MENU_SELECTION_FG_COLOR = BetterColorConstants.MENU_SELECTION_FG_COLOR;
	public static Color MENU_BORDER_COLOR = BetterColorConstants.MENU_BORDER_COLOR;

	public static Color MENU_ITEM_BG_COLOR = BetterColorConstants.MENU_ITEM_BG_COLOR;
	public static Color MENU_ITEM_FG_COLOR = BetterColorConstants.MENU_ITEM_FG_COLOR;
	public static Color MENU_ITEM_SELECTION_BG_COLOR = BetterColorConstants.MENU_ITEM_SELECTION_BG_COLOR;
	public static Color MENU_ITEM_SELECTION_FG_COLOR = BetterColorConstants.MENU_ITEM_SELECTION_FG_COLOR;

	public static Color SEPARATOR_BG_COLOR = BetterColorConstants.SEPARATOR_BG_COLOR;
	public static Color SEPARATOR_FG_COLOR = BetterColorConstants.SEPARATOR_FG_COLOR;

	public static Color LABEL_BG_COLOR = BetterColorConstants.LABEL_BG_COLOR;
	public static Color LABEL_FG_COLOR = BetterColorConstants.LABEL_FG_COLOR;

	public static Color BUTTON_BG_COLOR = BetterColorConstants.BUTTON_BG_COLOR;
	public static Color BUTTON_FG_COLOR = BetterColorConstants.BUTTON_FG_COLOR;
	public static Color BUTTON_SELECT_COLOR = BetterColorConstants.BUTTON_SELECT_COLOR;
	public static Color BUTTON_FOCUS_COLOR = BetterColorConstants.BUTTON_FOCUS_COLOR;
	public static Color BUTTON_BORDER_COLOR = BetterColorConstants.BUTTON_BORDER_COLOR;

	public static Color TOOLTIP_BG_COLOR = BetterColorConstants.TOOLTIP_BG_COLOR;
	public static Color TOOLTIP_FG_COLOR = BetterColorConstants.TOOLTIP_FG_COLOR;
	public static Color TOOLTIP_BORDER_COLOR = BetterColorConstants.TOOLTIP_BORDER_COLOR;

	public static Color CHECKBOX_BG_COLOR = BetterColorConstants.CHECKBOX_BG_COLOR;
	public static Color CHECKBOX_FG_COLOR = BetterColorConstants.CHECKBOX_FG_COLOR;
	public static Color CHECKBOX_FOCUS_COLOR = BetterColorConstants.CHECKBOX_FOCUS_COLOR;
	public static Color CHECKBOX_BOX_COLOR = BetterColorConstants.CHECKBOX_BOX_COLOR;
	public static Color CHECKBOX_ICON_COLOR = BetterColorConstants.CHECKBOX_ICON_COLOR;

	public static Color COMBOBOX_BG_COLOR = BetterColorConstants.COMBOBOX_BG_COLOR;
	public static Color COMBOBOX_FG_COLOR = BetterColorConstants.COMBOBOX_FG_COLOR;
	public static Color COMBOBOX_SELECTION_BG_COLOR = BetterColorConstants.COMBOBOX_SELECTION_BG_COLOR;
	public static Color COMBOBOX_SELECTION_FG_COLOR = BetterColorConstants.COMBOBOX_SELECTION_FG_COLOR;
	public static Color COMBOBOX_BORDER_COLOR = BetterColorConstants.COMBOBOX_BORDER_COLOR;
	public static Color COMBOBOX_BORDER_COLOR_CLICKED = BetterColorConstants.COMBOBOX_BORDER_COLOR_CLICKED;
	public static Color COMBOBOX_BUTTON_BG_COLOR = BetterColorConstants.COMBOBOX_BUTTON_BG_COLOR;
	public static Color COMBOBOX_BUTTON_DARK_SHADOW_COLOR = BetterColorConstants.COMBOBOX_BUTTON_DARK_SHADOW_COLOR;
	public static Color COMBOBOX_BUTTON_HIGHLIGHT_COLOR = BetterColorConstants.COMBOBOX_BUTTON_HIGHLIGHT_COLOR;
	public static Color COMBOBOX_BUTTON_SHADOW_COLOR = BetterColorConstants.COMBOBOX_BUTTON_SHADOW_COLOR;
	public static Color COMBOBOX_DISABLED_BG_COLOR = BetterColorConstants.COMBOBOX_DISABLED_BG_COLOR;
	public static Color COMBOBOX_DISABLED_FG_COLOR = BetterColorConstants.COMBOBOX_DISABLED_FG_COLOR;

	public static Color TXTFIELD_BG_COLOR = BetterColorConstants.TXTFIELD_BG_COLOR;
	public static Color TXTFIELD_FG_COLOR = BetterColorConstants.TXTFIELD_FG_COLOR;
	public static Color TXTFIELD_SELECTION_BG_COLOR = BetterColorConstants.TXTFIELD_SELECTION_BG_COLOR;
	public static Color TXTFIELD_SELECTION_FG_COLOR = BetterColorConstants.TXTFIELD_SELECTION_FG_COLOR;
	public static Color TXTFIELD_BORDER_COLOR = BetterColorConstants.TXTFIELD_BORDER_COLOR;
	public static Color TXTFIELD_DISABLED_BG_COLOR = BetterColorConstants.TXTFIELD_DISABLED_BG_COLOR;
	public static Color TXTFIELD_DISABLED_FG_COLOR = BetterColorConstants.TXTFIELD_DISABLED_FG_COLOR;

	public static Color TXTAREA_BG_COLOR = BetterColorConstants.TXTAREA_BG_COLOR;
	public static Color TXTAREA_FG_COLOR = BetterColorConstants.TXTAREA_FG_COLOR;
	public static Color TXTAREA_SELECTION_BG_COLOR = BetterColorConstants.TXTAREA_SELECTION_BG_COLOR;
	public static Color TXTAREA_SELECTION_FG_COLOR = BetterColorConstants.TXTAREA_SELECTION_FG_COLOR;
	public static Color TXTAREA_BORDER_COLOR = BetterColorConstants.TXTAREA_BORDER_COLOR;
	public static Color TXTAREA_INACTIVE_FG_COLOR = BetterColorConstants.TXTAREA_INACTIVE_FG_COLOR;

	public static Color CHECKBOX_MENU_ITEM_BG_COLOR = BetterColorConstants.CHECKBOX_MENU_ITEM_BG_COLOR;
	public static Color CHECKBOX_MENU_ITEM_FG_COLOR = BetterColorConstants.CHECKBOX_MENU_ITEM_FG_COLOR;
	public static Color CHECKBOX_MENU_ITEM_SELECTION_BG_COLOR = BetterColorConstants.CHECKBOX_MENU_ITEM_SELECTION_BG_COLOR;
	public static Color CHECKBOX_MENU_ITEM_SELECTION_FG_COLOR = BetterColorConstants.CHECKBOX_MENU_ITEM_SELECTION_FG_COLOR;
	public static Color CHECKBOX_MENU_ITEM_ICON_COLOR = BetterColorConstants.CHECKBOX_MENU_ITEM_ICON_COLOR;

	public static Color SLIDER_BG_COLOR = BetterColorConstants.SLIDER_BG_COLOR;
	public static Color SLIDER_TRACK_BG_COLOR = BetterColorConstants.SLIDER_TRACK_BG_COLOR;
	public static Color SLIDER_TRACK_FG_COLOR = BetterColorConstants.SLIDER_TRACK_FG_COLOR;
	public static Color SLIDER_MINOR_TICK_COLOR = BetterColorConstants.SLIDER_MINOR_TICK_COLOR;
	public static Color SLIDER_MAJOR_TICK_COLOR = BetterColorConstants.SLIDER_MAJOR_TICK_COLOR;

	public static Color POPUP_MENU_BG_COLOR = BetterColorConstants.POPUP_MENU_BG_COLOR;
	public static Color POPUP_MENU_FG_COLOR = BetterColorConstants.POPUP_MENU_FG_COLOR;
	public static Color POPUP_MENU_BORDER_COLOR = BetterColorConstants.POPUP_MENU_BORDER_COLOR;

	public static Color PANEL_BG_COLOR = BetterColorConstants.PANEL_BG_COLOR;
	public static Color PANEL_FG_COLOR = BetterColorConstants.PANEL_FG_COLOR;

	public static Color SCROLL_PANE_BG_COLOR = BetterColorConstants.SCROLL_PANE_BG_COLOR;
	public static Color SCROLL_PANE_FG_COLOR = BetterColorConstants.SCROLL_PANE_FG_COLOR;

	public static Color SCROLL_BAR_THUMB_COLOR = BetterColorConstants.SCROLL_BAR_THUMB_COLOR;
	public static Color SCROLL_BAR_TRACK_COLOR = BetterColorConstants.SCROLL_BAR_TRACK_COLOR;

	public static Color VIEWPORT_BG_COLOR = BetterColorConstants.VIEWPORT_BG_COLOR;
	public static Color VIEWPORT_FG_COLOR = BetterColorConstants.VIEWPORT_FG_COLOR;

	public static Color TABBED_PANE_BG_COLOR = BetterColorConstants.TABBED_PANE_BG_COLOR;
	public static Color TABBED_PANE_FG_COLOR = BetterColorConstants.TABBED_PANE_FG_COLOR;
	public static Color TABBED_PANE_SELECTED_FG_COLOR = BetterColorConstants.TABBED_PANE_SELECTED_FG_COLOR;
	public static Color TABBED_PANE_TAB_AREA_BG_COLOR = BetterColorConstants.TABBED_PANE_TAB_AREA_BG_COLOR;
	public static Color TABBED_PANE_BORDER_COLOR = BetterColorConstants.TABBED_PANE_BORDER_COLOR;
	public static Color TABBED_PANE_INNER_BORDER_COLOR = BetterColorConstants.TABBED_PANE_INNER_BORDER_COLOR;

	public static Color SPLIT_PANE_DIVIDER_GLOBAL_COLOR = BetterColorConstants.SPLIT_PANE_DIVIDER_GLOBAL_COLOR;
	public static Color SPLIT_PANE_DIVIDER_ARROW_COLOR = BetterColorConstants.SPLIT_PANE_DIVIDER_ARROW_COLOR;

	public static Color TOOLBAR_BG_COLOR = BetterColorConstants.TOOLBAR_BG_COLOR;
	public static Color TOOLBAR_BORDER_COLOR = BetterColorConstants.TOOLBAR_BORDER_COLOR;

	public static Color TITLED_BORDER_FONT_COLOR = BetterColorConstants.TITLED_BORDER_FONT_COLOR;
	public static Color TITLED_BORDER_BORDER_COLOR = BetterColorConstants.TITLED_BORDER_BORDER_COLOR;

	public static Color RADIO_BUTTON_BUTTON_BG_COLOR = BetterColorConstants.RADIO_BUTTON_BG_COLOR;
	public static Color RADIO_BUTTON_BUTTON_FG_COLOR = BetterColorConstants.RADIO_BUTTON_FG_COLOR;

	public static Color TABLE_GRID_COLOR = BetterColorConstants.TABLE_GRID_COLOR;
	public static Color TABLE_SELECTION_BORDER_COLOR = BetterColorConstants.TABLE_SELECTION_BORDER_COLOR;

	public static Color TABLE_HEADER_BG_COLOR = BetterColorConstants.TABLE_HEADER_BG_COLOR;
	public static Color TABLE_HEADER_FG_COLOR = BetterColorConstants.TABLE_HEADER_FG_COLOR;
	public static Color TABLE_HEADER_BORDER_COLOR = BetterColorConstants.TABLE_HEADER_BORDER_COLOR;

	public static Color OPTION_PANE_BG_COLOR = BetterColorConstants.OPTION_PANE_BG_COLOR;
	public static Color OPTION_PANE_FG_COLOR = BetterColorConstants.OPTION_PANE_FG_COLOR;

	public static Color EDITOR_PANE_BG_COLOR = BetterColorConstants.EDITOR_PANE_BG_COLOR;
	public static Color EDITOR_PANE_FG_COLOR = BetterColorConstants.EDITOR_PANE_FG_COLOR;
	public static Color EDITOR_PANE_SELECTION_BG_COLOR = BetterColorConstants.EDITOR_PANE_SELECTION_BG_COLOR;
	public static Color EDITOR_PANE_SELECTION_FG_COLOR = BetterColorConstants.EDITOR_PANE_SELECTION_FG_COLOR;

	public static Color INTERNAL_FRAME_TITLE_BG_COLOR = BetterColorConstants.INTERNAL_FRAME_TITLE_BG_COLOR;
	public static Color INTERNAL_FRAME_TITLE_FG_COLOR = BetterColorConstants.INTERNAL_FRAME_TITLE_FG_COLOR;
	public static Color INTERNAL_FRAME_BORDER_COLOR = BetterColorConstants.INTERNAL_FRAME_BORDER_COLOR;

	public static Color LIST_BG_COLOR = BetterColorConstants.LIST_BG_COLOR;
	public static Color LIST_FG_COLOR = BetterColorConstants.LIST_FG_COLOR;

	// NO UI MANAGER, FIDDLE CODE. Changed code, didn't used UIManager, cuz I
	// couldn't.
	public static Color TXT_BG_COLOR = BetterColorConstants.TXT_BG_COLOR;
	public static Color TXT_FG_COLOR = BetterColorConstants.TXT_FG_COLOR;
	public static Color TXT_SINGULAR_SEL_BG_COLOR = BetterColorConstants.TXT_SINGULAR_SEL_BG_COLOR;
	public static Color TXT_MULTIPLE_SEL_BG_COLOR = BetterColorConstants.TXT_MULTIPLE_SEL_BG_COLOR;
	public static Color TXT_CARET_COLOR = BetterColorConstants.TXT_CARET_COLOR;

	// MARS ONLY
	public static Color HELP_LABEL_BG_COLOR = BetterColorConstants.HELP_LABEL_BG_COLOR;
	public static Color HELP_LABEL_FG_COLOR = BetterColorConstants.HELP_LABEL_FG_COLOR;
	public static Color HELP_LABEL_SELECTION_BG_COLOR = BetterColorConstants.HELP_LABEL_SELECTION_BG_COLOR;
	public static Color HELP_LABEL_SELECTION_FG_COLOR = BetterColorConstants.HELP_LABEL_SELECTION_FG_COLOR;

	public static Color TXT_SEGMENT_HIGHLIGHT_BG_COLOR = BetterColorConstants.TXT_SEGMENT_HIGHLIGHT_BG_COLOR;
	public static Color TXT_SEGMENT_HIGHLIGHT_FG_COLOR = BetterColorConstants.TXT_SEGMENT_HIGHLIGHT_FG_COLOR;
	public static Color TXT_SEGMENT_DELAY_SLOT_HIGHLIGHT_BG_COLOR = BetterColorConstants.TXT_SEGMENT_DELAY_SLOT_HIGHLIGHT_BG_COLOR;
	public static Color TXT_SEGMENT_DELAY_SLOT_HIGHLIGHT_FG_COLOR = BetterColorConstants.TXT_SEGMENT_DELAY_SLOT_HIGHLIGHT_FG_COLOR;

	public static Color DATA_SEGMENT_HIGHLIGHT_BG_COLOR = BetterColorConstants.DATA_SEGMENT_HIGHLIGHT_BG_COLOR;
	public static Color DATA_SEGMENT_HIGHLIGHT_FG_COLOR = BetterColorConstants.DATA_SEGMENT_HIGHLIGHT_FG_COLOR;

	public static Color REGISTER_HIGHLIGHT_BG_COLOR = BetterColorConstants.REGISTER_HIGHLIGHT_BG_COLOR;
	public static Color REGISTER_HIGHLIGHT_FG_COLOR = BetterColorConstants.REGISTER_HIGHLIGHT_FG_COLOR;

	public static Color TABLE_EVEN_ROW_BG = BetterColorConstants.TABLE_EVEN_ROW_BG;
	public static Color TABLE_EVEN_ROW_FG = BetterColorConstants.TABLE_EVEN_ROW_FG;
	public static Color TABLE_ODD_ROW_BG = BetterColorConstants.TABLE_ODD_ROW_BG;
	public static Color TABLE_ODD_ROW_FG = BetterColorConstants.TABLE_ODD_ROW_FG;

	public static Color ADDRESS_BG_COLOR = BetterColorConstants.ADDRESS_BG_COLOR;
	public static Color ADDRESS_FG_COLOR = BetterColorConstants.ADDRESS_FG_COLOR;

	public static Color MESSAGES_PANE_ERROR_TEXT_BG_COLOR = BetterColorConstants.MESSAGES_PANE_ERROR_TEXT_BG_COLOR;
	public static Color MESSAGES_PANE_ERROR_TEXT_FG_COLOR = BetterColorConstants.MESSAGES_PANE_ERROR_TEXT_FG_COLOR;

	public static Color[] savedColors = { MENU_BAR_BG_COLOR, MENU_BG_COLOR, MENU_FG_COLOR, MENU_SELECTION_BG_COLOR, MENU_SELECTION_FG_COLOR, MENU_BORDER_COLOR,
	        MENU_ITEM_BG_COLOR, MENU_ITEM_FG_COLOR, MENU_ITEM_SELECTION_BG_COLOR, MENU_ITEM_SELECTION_FG_COLOR, SEPARATOR_BG_COLOR, SEPARATOR_FG_COLOR, LABEL_BG_COLOR,
	        LABEL_FG_COLOR, BUTTON_BG_COLOR, BUTTON_FG_COLOR, BUTTON_SELECT_COLOR, BUTTON_FOCUS_COLOR, BUTTON_BORDER_COLOR, TOOLTIP_BG_COLOR, TOOLTIP_FG_COLOR,
	        TOOLTIP_BORDER_COLOR, CHECKBOX_BG_COLOR, CHECKBOX_FG_COLOR, CHECKBOX_FOCUS_COLOR, CHECKBOX_BOX_COLOR, CHECKBOX_ICON_COLOR, COMBOBOX_BG_COLOR,
	        COMBOBOX_FG_COLOR, COMBOBOX_SELECTION_BG_COLOR, COMBOBOX_SELECTION_FG_COLOR, COMBOBOX_BORDER_COLOR, COMBOBOX_BUTTON_BG_COLOR, COMBOBOX_DISABLED_BG_COLOR,
	        COMBOBOX_DISABLED_FG_COLOR, COMBOBOX_BUTTON_SHADOW_COLOR, COMBOBOX_BUTTON_DARK_SHADOW_COLOR, COMBOBOX_BUTTON_HIGHLIGHT_COLOR, TXTFIELD_BG_COLOR,
	        TXTFIELD_FG_COLOR, TXTFIELD_SELECTION_BG_COLOR, TXTFIELD_SELECTION_FG_COLOR, TXTFIELD_BORDER_COLOR, TXTFIELD_DISABLED_BG_COLOR, TXTFIELD_DISABLED_FG_COLOR,
	        TXTAREA_BG_COLOR, TXTAREA_FG_COLOR, TXTAREA_SELECTION_BG_COLOR, TXTAREA_SELECTION_FG_COLOR, TXTAREA_BORDER_COLOR, TXTAREA_INACTIVE_FG_COLOR,
	        CHECKBOX_MENU_ITEM_BG_COLOR, CHECKBOX_MENU_ITEM_FG_COLOR, CHECKBOX_MENU_ITEM_SELECTION_BG_COLOR, CHECKBOX_MENU_ITEM_SELECTION_FG_COLOR,
	        CHECKBOX_MENU_ITEM_ICON_COLOR, SLIDER_BG_COLOR, SLIDER_TRACK_BG_COLOR, SLIDER_TRACK_FG_COLOR, SLIDER_MINOR_TICK_COLOR, SLIDER_MAJOR_TICK_COLOR,
	        POPUP_MENU_BG_COLOR, POPUP_MENU_FG_COLOR, POPUP_MENU_BORDER_COLOR, PANEL_BG_COLOR, PANEL_FG_COLOR, SCROLL_PANE_BG_COLOR, SCROLL_PANE_FG_COLOR,
	        SCROLL_BAR_TRACK_COLOR, SCROLL_BAR_THUMB_COLOR, VIEWPORT_BG_COLOR, VIEWPORT_FG_COLOR, TABBED_PANE_BG_COLOR, TABBED_PANE_FG_COLOR,
	        TABBED_PANE_SELECTED_FG_COLOR, TABBED_PANE_TAB_AREA_BG_COLOR, TABBED_PANE_BORDER_COLOR, TABBED_PANE_INNER_BORDER_COLOR, SPLIT_PANE_DIVIDER_GLOBAL_COLOR,
	        SPLIT_PANE_DIVIDER_ARROW_COLOR, TOOLBAR_BG_COLOR, TOOLBAR_BORDER_COLOR, TITLED_BORDER_FONT_COLOR, TITLED_BORDER_BORDER_COLOR, TABLE_GRID_COLOR,
	        TABLE_SELECTION_BORDER_COLOR, TABLE_HEADER_BG_COLOR, TABLE_HEADER_FG_COLOR, TABLE_HEADER_BORDER_COLOR, OPTION_PANE_BG_COLOR, OPTION_PANE_FG_COLOR,
	        EDITOR_PANE_BG_COLOR, EDITOR_PANE_FG_COLOR, EDITOR_PANE_SELECTION_BG_COLOR, EDITOR_PANE_SELECTION_FG_COLOR, INTERNAL_FRAME_TITLE_BG_COLOR,
	        INTERNAL_FRAME_TITLE_FG_COLOR, INTERNAL_FRAME_BORDER_COLOR, LIST_BG_COLOR, LIST_FG_COLOR, TXT_BG_COLOR, TXT_FG_COLOR, TXT_SINGULAR_SEL_BG_COLOR,
	        TXT_MULTIPLE_SEL_BG_COLOR, TXT_CARET_COLOR, HELP_LABEL_BG_COLOR, HELP_LABEL_FG_COLOR, HELP_LABEL_SELECTION_BG_COLOR, HELP_LABEL_SELECTION_FG_COLOR,
	        TXT_SEGMENT_HIGHLIGHT_BG_COLOR, TXT_SEGMENT_HIGHLIGHT_FG_COLOR, TXT_SEGMENT_DELAY_SLOT_HIGHLIGHT_BG_COLOR, TXT_SEGMENT_DELAY_SLOT_HIGHLIGHT_FG_COLOR,
	        DATA_SEGMENT_HIGHLIGHT_BG_COLOR, DATA_SEGMENT_HIGHLIGHT_FG_COLOR, REGISTER_HIGHLIGHT_BG_COLOR, REGISTER_HIGHLIGHT_FG_COLOR, TABLE_EVEN_ROW_BG,
	        TABLE_EVEN_ROW_FG, TABLE_ODD_ROW_BG, TABLE_ODD_ROW_FG, ADDRESS_BG_COLOR, ADDRESS_FG_COLOR, MESSAGES_PANE_ERROR_TEXT_BG_COLOR,
	        MESSAGES_PANE_ERROR_TEXT_FG_COLOR };

	public static Color[] defaultDarkColors = { MENU_BAR_BG_COLOR, MENU_BG_COLOR, MENU_FG_COLOR, MENU_SELECTION_BG_COLOR, MENU_SELECTION_FG_COLOR, MENU_BORDER_COLOR,
	        MENU_ITEM_BG_COLOR, MENU_ITEM_FG_COLOR, MENU_ITEM_SELECTION_BG_COLOR, MENU_ITEM_SELECTION_FG_COLOR, SEPARATOR_BG_COLOR, SEPARATOR_FG_COLOR, LABEL_BG_COLOR,
	        LABEL_FG_COLOR, BUTTON_BG_COLOR, BUTTON_FG_COLOR, BUTTON_SELECT_COLOR, BUTTON_FOCUS_COLOR, BUTTON_BORDER_COLOR, TOOLTIP_BG_COLOR, TOOLTIP_FG_COLOR,
	        TOOLTIP_BORDER_COLOR, CHECKBOX_BG_COLOR, CHECKBOX_FG_COLOR, CHECKBOX_FOCUS_COLOR, CHECKBOX_BOX_COLOR, CHECKBOX_ICON_COLOR, COMBOBOX_BG_COLOR,
	        COMBOBOX_FG_COLOR, COMBOBOX_SELECTION_BG_COLOR, COMBOBOX_SELECTION_FG_COLOR, COMBOBOX_BORDER_COLOR, COMBOBOX_BUTTON_BG_COLOR, COMBOBOX_DISABLED_BG_COLOR,
	        COMBOBOX_DISABLED_FG_COLOR, COMBOBOX_BUTTON_SHADOW_COLOR, COMBOBOX_BUTTON_DARK_SHADOW_COLOR, COMBOBOX_BUTTON_HIGHLIGHT_COLOR, TXTFIELD_BG_COLOR,
	        TXTFIELD_FG_COLOR, TXTFIELD_SELECTION_BG_COLOR, TXTFIELD_SELECTION_FG_COLOR, TXTFIELD_BORDER_COLOR, TXTFIELD_DISABLED_BG_COLOR, TXTFIELD_DISABLED_FG_COLOR,
	        TXTAREA_BG_COLOR, TXTAREA_FG_COLOR, TXTAREA_SELECTION_BG_COLOR, TXTAREA_SELECTION_FG_COLOR, TXTAREA_BORDER_COLOR, TXTAREA_INACTIVE_FG_COLOR,
	        CHECKBOX_MENU_ITEM_BG_COLOR, CHECKBOX_MENU_ITEM_FG_COLOR, CHECKBOX_MENU_ITEM_SELECTION_BG_COLOR, CHECKBOX_MENU_ITEM_SELECTION_FG_COLOR,
	        CHECKBOX_MENU_ITEM_ICON_COLOR, SLIDER_BG_COLOR, SLIDER_TRACK_BG_COLOR, SLIDER_TRACK_FG_COLOR, SLIDER_MINOR_TICK_COLOR, SLIDER_MAJOR_TICK_COLOR,
	        POPUP_MENU_BG_COLOR, POPUP_MENU_FG_COLOR, POPUP_MENU_BORDER_COLOR, PANEL_BG_COLOR, PANEL_FG_COLOR, SCROLL_PANE_BG_COLOR, SCROLL_PANE_FG_COLOR,
	        SCROLL_BAR_TRACK_COLOR, SCROLL_BAR_THUMB_COLOR, VIEWPORT_BG_COLOR, VIEWPORT_FG_COLOR, TABBED_PANE_BG_COLOR, TABBED_PANE_FG_COLOR,
	        TABBED_PANE_SELECTED_FG_COLOR, TABBED_PANE_TAB_AREA_BG_COLOR, TABBED_PANE_BORDER_COLOR, TABBED_PANE_INNER_BORDER_COLOR, SPLIT_PANE_DIVIDER_GLOBAL_COLOR,
	        SPLIT_PANE_DIVIDER_ARROW_COLOR, TOOLBAR_BG_COLOR, TOOLBAR_BORDER_COLOR, TITLED_BORDER_FONT_COLOR, TITLED_BORDER_BORDER_COLOR, TABLE_GRID_COLOR,
	        TABLE_SELECTION_BORDER_COLOR, TABLE_HEADER_BG_COLOR, TABLE_HEADER_FG_COLOR, TABLE_HEADER_BORDER_COLOR, OPTION_PANE_BG_COLOR, OPTION_PANE_FG_COLOR,
	        EDITOR_PANE_BG_COLOR, EDITOR_PANE_FG_COLOR, EDITOR_PANE_SELECTION_BG_COLOR, EDITOR_PANE_SELECTION_FG_COLOR, INTERNAL_FRAME_TITLE_BG_COLOR,
	        INTERNAL_FRAME_TITLE_FG_COLOR, INTERNAL_FRAME_BORDER_COLOR, LIST_BG_COLOR, LIST_FG_COLOR, TXT_BG_COLOR, TXT_FG_COLOR, TXT_SINGULAR_SEL_BG_COLOR,
	        TXT_MULTIPLE_SEL_BG_COLOR, TXT_CARET_COLOR, HELP_LABEL_BG_COLOR, HELP_LABEL_FG_COLOR, HELP_LABEL_SELECTION_BG_COLOR, HELP_LABEL_SELECTION_FG_COLOR,
	        TXT_SEGMENT_HIGHLIGHT_BG_COLOR, TXT_SEGMENT_HIGHLIGHT_FG_COLOR, TXT_SEGMENT_DELAY_SLOT_HIGHLIGHT_BG_COLOR, TXT_SEGMENT_DELAY_SLOT_HIGHLIGHT_FG_COLOR,
	        DATA_SEGMENT_HIGHLIGHT_BG_COLOR, DATA_SEGMENT_HIGHLIGHT_FG_COLOR, REGISTER_HIGHLIGHT_BG_COLOR, REGISTER_HIGHLIGHT_FG_COLOR, TABLE_EVEN_ROW_BG,
	        TABLE_EVEN_ROW_FG, TABLE_ODD_ROW_BG, TABLE_ODD_ROW_FG, ADDRESS_BG_COLOR, ADDRESS_FG_COLOR, MESSAGES_PANE_ERROR_TEXT_BG_COLOR,
	        MESSAGES_PANE_ERROR_TEXT_FG_COLOR };

	public static Color[] defaultColors = { new Color(238, 238, 238), new Color(238, 238, 238), new Color(51, 51, 51), new Color(163, 184, 204), new Color(51, 51, 51),
	        new Color(238, 238, 238), new Color(238, 238, 238), new Color(51, 51, 51), new Color(163, 184, 204), new Color(51, 51, 51), new Color(255, 255, 255),
	        new Color(99, 130, 191), new Color(238, 238, 238), new Color(51, 51, 51), new Color(238, 238, 238), new Color(51, 51, 51), new Color(184, 207, 229),
	        new Color(163, 184, 204), new Color(122, 138, 153), new Color(184, 207, 229), new Color(51, 51, 51), new Color(99, 130, 191), new Color(255, 255, 255),
	        new Color(51, 51, 51), new Color(163, 184, 204), new Color(184, 207, 229), new Color(51, 51, 51), new Color(238, 238, 238), new Color(51, 51, 51),
	        new Color(163, 184, 204), new Color(51, 51, 51), COMBOBOX_BORDER_COLOR, COMBOBOX_BUTTON_BG_COLOR, new Color(238, 238, 238), new Color(163, 184, 204),
	        COMBOBOX_BUTTON_SHADOW_COLOR, COMBOBOX_BUTTON_DARK_SHADOW_COLOR, COMBOBOX_BUTTON_HIGHLIGHT_COLOR, new Color(255, 255, 255), new Color(51, 51, 51),
	        new Color(184, 207, 229), new Color(51, 51, 51), new Color(122, 138, 153), new Color(238, 238, 238), new Color(184, 207, 229), new Color(255, 255, 255),
	        new Color(51, 51, 51), new Color(184, 207, 229), new Color(51, 51, 51), new Color(122, 138, 153), new Color(184, 207, 229), new Color(238, 238, 238),
	        new Color(51, 51, 51), new Color(163, 184, 204), new Color(51, 51, 51), new Color(51, 51, 51), new Color(99, 130, 191), new Color(238, 238, 238),
	        new Color(184, 207, 229), SLIDER_MINOR_TICK_COLOR, SLIDER_MAJOR_TICK_COLOR, new Color(238, 238, 238), new Color(51, 51, 51), POPUP_MENU_BORDER_COLOR,
	        new Color(238, 238, 238), new Color(51, 51, 51), new Color(238, 238, 238), new Color(51, 51, 51), new Color(238, 238, 238), new Color(200, 218, 235),
	        new Color(238, 238, 238), new Color(51, 51, 51), new Color(184, 207, 229), new Color(51, 51, 51), new Color(51, 51, 51), new Color(255, 0, 0),
	        new Color(122, 138, 153), new Color(255, 255, 255), new Color(238, 238, 238), new Color(90, 130, 191), new Color(238, 238, 238), new Color(153, 153, 153),
	        new Color(51, 51, 51), new Color(184, 207, 229), new Color(122, 138, 153), new Color(99, 130, 191), new Color(238, 238, 238), new Color(51, 51, 51),
	        new Color(122, 138, 153), new Color(238, 238, 238), new Color(51, 51, 51), new Color(255, 255, 255), new Color(51, 51, 51), new Color(184, 207, 229),
	        new Color(51, 51, 51), new Color(184, 207, 229), new Color(51, 51, 51), new Color(99, 130, 191), new Color(255, 255, 255), new Color(51, 51, 51),
	        new Color(255, 255, 255), new Color(0, 0, 0), new Color(238, 238, 238), new Color(204, 204, 255), new Color(0, 0, 0), new Color(255, 255, 153),
	        new Color(0, 0, 0), new Color(184, 207, 229), new Color(0, 0, 0), new Color(255, 255, 153), new Color(0, 0, 0), new Color(51, 255, 0), new Color(0, 0, 0),
	        new Color(153, 204, 255), new Color(0, 0, 0), new Color(153, 204, 85), new Color(0, 0, 0), new Color(224, 224, 224), new Color(0, 0, 0),
	        new Color(255, 255, 255), new Color(0, 0, 0), new Color(255, 255, 255), new Color(0, 0, 0), new Color(255, 255, 0), new Color(0, 0, 0) };

	public static Color[] currentColors = defaultDarkColors;

	public static void revertColorChanges() {
		for (int i = 0; i < currentColors.length; i++) {
			currentColors[i] = savedColors[i];
		}
	}

	public static void saveColorChanges() {
		for (int i = 0; i < savedColors.length; i++) {
			savedColors[i] = currentColors[i];
		}
	}
}
